[package]
name = "gmdn"
version = "0.1.0"
authors = ["Nathaniel Clark <Nathaniel.Clark@misrule.us>"]
edition = "2018"

[dependencies]
clap = { version = "4", features = ["std", "derive", "help", "usage"], default-features = false  }
